"""empty message

Revision ID: 3494db33ed0d
Revises: ed29afe12d42
Create Date: 2021-11-26 15:10:20.842084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3494db33ed0d'
down_revision = 'ed29afe12d42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'species', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'species', type_='unique')
    # ### end Alembic commands ###
