"""empty message

Revision ID: 41592fba235c
Revises: 3c6f67d23ac0
Create Date: 2021-11-16 15:04:01.783468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41592fba235c'
down_revision = '3c6f67d23ac0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourite_people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('people_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite_people')
    op.drop_table('favourite')
    # ### end Alembic commands ###
