"""empty message

Revision ID: 60bb22e4b79d
Revises: b8a0c08f770a
Create Date: 2021-11-16 10:55:02.999429

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60bb22e4b79d'
down_revision = 'b8a0c08f770a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('url', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
