"""empty message

Revision ID: 75923dca927b
Revises: 3494db33ed0d
Create Date: 2021-11-28 11:50:25.486696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75923dca927b'
down_revision = '3494db33ed0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('people_detail', 'hair_color')
    op.drop_column('people_detail', 'skin_color')
    op.drop_column('people_detail', 'mass')
    op.drop_column('people_detail', 'height')
    op.drop_column('people_detail', 'created')
    op.drop_column('people_detail', 'birth_year')
    op.drop_column('people_detail', 'edited')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_detail', sa.Column('edited', mysql.DATETIME(), nullable=False))
    op.add_column('people_detail', sa.Column('birth_year', mysql.DATETIME(), nullable=False))
    op.add_column('people_detail', sa.Column('created', mysql.DATETIME(), nullable=False))
    op.add_column('people_detail', sa.Column('height', mysql.FLOAT(), nullable=False))
    op.add_column('people_detail', sa.Column('mass', mysql.FLOAT(), nullable=False))
    op.add_column('people_detail', sa.Column('skin_color', mysql.VARCHAR(length=250), nullable=False))
    op.add_column('people_detail', sa.Column('hair_color', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
