"""empty message

Revision ID: b8a0c08f770a
Revises: de96afcb3dc5
Create Date: 2021-11-16 10:23:51.089274

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8a0c08f770a'
down_revision = 'de96afcb3dc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people', sa.Column('detail_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'people', 'people_detail', ['detail_id'], ['id'])
    op.drop_column('people_detail', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('people_detail', sa.Column('url', mysql.VARCHAR(length=250), nullable=False))
    op.drop_constraint(None, 'people', type_='foreignkey')
    op.drop_column('people', 'detail_id')
    # ### end Alembic commands ###
