"""empty message

Revision ID: ed29afe12d42
Revises: 11ece2f9da87
Create Date: 2021-11-21 22:07:29.883319

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ed29afe12d42'
down_revision = '11ece2f9da87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite_character', sa.Column('people_id', sa.Integer(), nullable=True))
    op.drop_constraint('favourite_character_ibfk_1', 'favourite_character', type_='foreignkey')
    op.create_foreign_key(None, 'favourite_character', 'people', ['people_id'], ['id'])
    op.drop_column('favourite_character', 'favourite_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favourite_character', sa.Column('favourite_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favourite_character', type_='foreignkey')
    op.create_foreign_key('favourite_character_ibfk_1', 'favourite_character', 'people', ['favourite_id'], ['id'])
    op.drop_column('favourite_character', 'people_id')
    # ### end Alembic commands ###
